CREATE TABLE JGO_USER(
USR_NICKNAME VARCHAR(12) NOT NULL,
USR_NAME VARCHAR(40) NOT NULL,
USR_PASSWORD VARCHAR(16) NOT NULL,
USR_FOTO VARCHAR(90),
USR_XP INTEGER NOT NULL,
USR_LEVEL INTEGER NOT NULL,
USR_FOTO_POR_LEVEL VARCHAR(90)
);